### ISSUE TITLE
categorizer.rb:31:in `initialize': undefined method `text' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ibrokemypie** [Lyle-Tafoya/Steam-Categorizer#25] opened 2017-06-26 11:38 UTC
getting this error whenever I try to use your app
```
$ steam-categorizer -p ~/Steam-Categorizer/example/steam_categorizer.json -c ~/.steam/steam/userdata/97404444/config/localconfig.vdf
 INFO  Steam::Categorizer::GameLibrary : Getting list of games...
/usr/lib/ruby/gems/2.4.0/gems/steam-categorizer-0.5.9/lib/steam/categorizer.rb:31:in `initialize': undefined method `text' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/gems/2.4.0/gems/steam-categorizer-0.5.9/exe/steam-categorizer:21:in `new'
	from /usr/lib/ruby/gems/2.4.0/gems/steam-categorizer-0.5.9/exe/steam-categorizer:21:in `<top (required)>'
	from /usr/bin/steam-categorizer:22:in `load'
	from /usr/bin/steam-categorizer:22:in `<main>'

```
I have tried with different paths, with and without config, and with gui, always fails the same way.
also, had trouble installing because I didnt realise I needed these deps which are not built/mentioned bundler, ruby-devel, gobject-introspection

**Comment by Lyle-Tafoya** [comment] 2017-06-26 13:44
I believe this is a duplicate of #23. Please see that issue for more information.

As far as the dependencies go, did you use `rake install` or `bundle install` in order to ensure that all dependencies are fetched automatically?

**Comment by ibrokemypie** [comment] 2017-06-26 13:46
Yes, I had, they were not being built, although I think that that was actually because I was missing ruby-devel an gobject-introspection

**Closed as completed** 2017-06-26 14:30 UTC
Labels: duplicate
